//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPAdminGroup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PROYECTOEntities1 : DbContext
    {
        public DB_PROYECTOEntities1()
            : base("name=DB_PROYECTOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Persona> Persona { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Modulo> Modulo { get; set; }
        public DbSet<Operaciones> Operaciones { get; set; }
        public DbSet<Rol_Operacion> Rol_Operacion { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
