//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPAdminGroup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int id { get; set; }
        [Required]
        public string nombre { get; set; }
        [Required]
        public string apelllido { get; set; }
        [Required]
        public string telefono { get; set; }
        [Required]
        public string direccion { get; set; }
        public string descripcion { get; set; }
        public byte[] image { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
