//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPAdminGroup.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public Usuario()
        {
            this.Persona = new HashSet<Persona>();
        }

        public int id { get; set; }

        [Required]
        public string usuario1 { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "El número de caracteres de {0} debe ser al menos {2}.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string contraseña { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar contraseña")]
        [Compare("contraseña", ErrorMessage = "La contraseña y la contraseña de confirmación no coinciden.")]
        public string confirmar_contraseña { get; set; }

        [Required]
        [Display(Name = "Correo electrónico")]
        [EmailAddress]
        public string correo { get; set; }
        public Nullable<bool> confirmarEmail { get; set; }
        public string tokenCorreo { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public string tokenContraseña { get; set; }

        public virtual ICollection<Persona> Persona { get; set; }
    }
}